[phases.setup]
nixPkgs = ["python311", "gcc"]
[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]
[phases.build]
cmds = ["echo 'build done'"]

[start]
cmd = "/opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300"
